# Generated by Django 6.0.6 on 2026-06-04 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('room_type', models.CharField(choices=[('TRAINER', 'Trainer Room'), ('GIRLS', 'Girls Hostel'), ('BOYS', 'Boys Hostel')], max_length=10)),
                ('capacity', models.IntegerField(default=2)),
                ('is_under_repair', models.BooleanField(default=False)),
                ('gender_category', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('current_occupancy', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('batch', models.CharField(choices=[('FSWD', 'FSWD'), ('AIML', 'AIML'), ('DEVOPS', 'DevOps')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('allocation_status', models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('VACATED', 'Vacated')], default='PENDING', max_length=15)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('allocation_type', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], default='AUTO', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hostel.room')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='hostel.student')),
            ],
            options={
                'ordering': ['-allocated_at'],
            },
        ),
    ]
