# Generated by Django 6.0.6 on 2026-06-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('is_under_repair', models.BooleanField(default=False)),
                ('gender_type', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('trainer', 'Trainer')], default='boys', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room')),
            ],
        ),
    ]
